[package]
name = "example-alerts"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
autometrics = { path = "../../autometrics", features = ["alerts"] }
clap = { version = "4.1", features = ["derive"]}
