scrape_configs:
  - job_name: example-api-metrics
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:3000']
    # For a real deployment, you would want the scrape interval to be
    # much longer but this is just for demo purposes and we want the
    # data to show up quickly
    scrape_interval: 200ms
    honor_labels: false
    honor_timestamps: true
    scheme: http
    follow_redirects: true
    body_size_limit: 0
    sample_limit: 0
    label_limit: 0
    label_name_length_limit: 0
    label_value_length_limit: 0
    target_limit: 0
