[package]
name = "autometrics-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
percent-encoding = "2.2"
proc-macro2 = "1"
quote = "1"
syn =  { version = "1", default-features = false }
