on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: CI

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      # Build the packages
      - run: cargo build
      - run: cargo build --features=custom-objective-percentile,custom-objective-latency

      # Run the tests with each of the different metrics libraries
      - run: cargo test --features=prometheus-exporter
      - run: cargo test --no-default-features --features=prometheus-exporter,metrics --tests
      - run: cargo test --no-default-features --features=prometheus-exporter,prometheus --tests
      - run: cargo test --no-default-features --features=prometheus-exporter,prometheus-client --tests

      # Compile the examples
      - run: cargo build --package example-axum
      - run: cargo build --package example-custom-metrics
      - run: cargo build --package example-full-api
