on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: CI

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      # Lint
      - name: Run Clippy
        # GitHub hosted runners using the latest stable version of Rust have Clippy pre-installed.
        run: cargo clippy --all-targets --features=prometheus-exporter,opentelemetry,metrics,prometheus

      # Build the packages
      - run: cargo build
      - run: cargo build --features=metrics
      - run: cargo build --features=prometheus
      - run: cargo build --features=custom-objective-percentile,custom-objective-latency

      # Run the tests
      - run: cargo test --features=prometheus-exporter

      # Compile the examples
      - run: cargo build --package example-axum
      - run: cargo build --package example-custom-metrics
      - run: cargo build --package example-full-api
