scrape_configs:
  - job_name: example-api-metrics
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:3000']
    # For a real deployment, you would want the scrape interval to be
    # much longer but this is just for demo purposes and we want the
    # data to show up quickly
    scrape_interval: 200ms
